### ISSUE TITLE
Initialization error with vue3 and nuxt3

### ISSUE THREAD

**Issue by nicopapy** [leongersen/noUiSlider#1220]
With the simple integration example given in the documentation, i got this error on page load (i'm using vue3 and nuxt3) : 

`Uncaught (in promise) ReferenceError: Cannot access 'scope_Self' before initialization
    at nouislider.ts:2438:25
    at Array.forEach (<anonymous>)
    at nouislider.ts:2435:43
    at Array.forEach (<anonymous>)
    at fireEvent (nouislider.ts:2431:35)
    at nouislider.ts:2403:17
    at Array.forEach (<anonymous>)
    at bindEvent (nouislider.ts:2402:27)
    at tooltips (nouislider.ts:1526:9)
    at setupSlider (nouislider.ts:2999:13)` 

I have the same integration working in vue2. Any idea ?

**Comment by leongersen** [comment]
I haven't seen this before. Is your code running before the node in the DOM is ready?

**Comment by mitar** [comment]
It works for me with Vue3. I think you should provide a more complete example.

**Comment by leongersen** [comment]
Thanks for the feedback @mitar, I'll close this. Feel free to open a new issue with more details if needed.
